#!/usr/bin/env python

import os, sys
import vobject

def usage():
    print "Usage: " + sys.argv[0] + " /path/to/vcf"

def gen(idx, entries, card):
    lines = {}
    if hasattr(card, 'fn'):
        name = card.fn.value
        i = 1
        while name in entries:
            name = "%s (%d)" % (name, i)
            i += 1
        lines["name"] = name
    else:
        return (idx, entries)

    if hasattr(card, 'tel'):
        for tel in card.tel_list:
            if tel.type_param == 'HOME':
                lines["p.phone"] = tel.value
            elif tel.type_param == 'CELL':
                lines["p.cellular"] = tel.value
            elif tel.type_param == 'WORK':
                lines["w.phone"] = tel.value
            else:
                lines["r.phone"] = tel.value
    else:
        return (idx, entries)

    if hasattr(card, 'email'):
        for email in card.email_list:
            if email.type_param == 'HOME':
                lines["p.email"] = email.value
            elif email.type_param == 'WORK':
                lines["w.email"] = email.value
            else:
                lines["r.email"] = email.value

    print u"@person{entry%03d," % (idx, )
    print ", \n".join(map(lambda (k,v): (u"%s = \"%s\"" % (k, v)).encode('utf8'), lines.items()))
    print u"}\n"

    entries.add(lines["name"])
    return (idx+1, entries)

def init_parse(cards):
    entries = set()
    parse(1, entries, cards)

def parse(idx, entries, cards):
    try:
        (newidx, entries2) = gen(idx, entries, cards.next())
        parse(newidx, entries2, cards)
    except StopIteration:
        pass

def main(args):
    if (len(args) < 1):
        usage()
        sys.exit(1)

    if (not os.path.exists(args[0])):
        print "E: Invalid path " + args[0]
        sys.exit(1)

    with open(args[0]) as f:
        init_parse(vobject.readComponents(f))

    sys.exit(0)
    
if __name__ == '__main__':
    main(sys.argv[1:])
